// <auto-generated />
using System;
using MagicVilla.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MagicVilla.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251023051811_InitialCreateWithSeed")]
    partial class InitialCreateWithSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MagicVilla.Domain.Entities.Villa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Created_Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Details")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Occupancy")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("Sqft")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Updated_Date")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Villas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created_Date = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Details = "This is the Royal Villa",
                            ImageUrl = "",
                            Name = "Royal Villa",
                            Occupancy = 4,
                            Price = 200.0,
                            Sqft = 550
                        },
                        new
                        {
                            Id = 2,
                            Created_Date = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Details = "This is the Premium Pool Villa",
                            ImageUrl = "",
                            Name = "Premium Pool Villa",
                            Occupancy = 4,
                            Price = 300.0,
                            Sqft = 550
                        },
                        new
                        {
                            Id = 3,
                            Created_Date = new DateTime(2024, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Details = "Spacious villa with private garden",
                            ImageUrl = "",
                            Name = "Luxury Garden Villa",
                            Occupancy = 5,
                            Price = 250.0,
                            Sqft = 600
                        },
                        new
                        {
                            Id = 4,
                            Created_Date = new DateTime(2024, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Details = "Perfect for family vacation stays",
                            ImageUrl = "",
                            Name = "Family Villa",
                            Occupancy = 6,
                            Price = 180.0,
                            Sqft = 500
                        },
                        new
                        {
                            Id = 5,
                            Created_Date = new DateTime(2024, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Details = "Romantic villa with ocean view and jacuzzi",
                            ImageUrl = "",
                            Name = "Honeymoon Suite Villa",
                            Occupancy = 2,
                            Price = 350.0,
                            Sqft = 450
                        });
                });

            modelBuilder.Entity("MagicVilla.Domain.Entities.VillaNumber", b =>
                {
                    b.Property<int>("VillaNo")
                        .HasColumnType("int");

                    b.Property<string>("SpecialDetails")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VillaId")
                        .HasColumnType("int");

                    b.HasKey("VillaNo");

                    b.HasIndex("VillaId");

                    b.ToTable("VillaNumbers");

                    b.HasData(
                        new
                        {
                            VillaNo = 101,
                            SpecialDetails = "This is the Royal Villa Number 101",
                            VillaId = 1
                        },
                        new
                        {
                            VillaNo = 102,
                            SpecialDetails = "This is the Royal Villa Number 102",
                            VillaId = 1
                        },
                        new
                        {
                            VillaNo = 201,
                            SpecialDetails = "This is the Premium Villa Number 201",
                            VillaId = 2
                        },
                        new
                        {
                            VillaNo = 202,
                            SpecialDetails = "This is the Premium Villa Number 202",
                            VillaId = 2
                        },
                        new
                        {
                            VillaNo = 301,
                            SpecialDetails = "Luxury Garden Villa No. 301",
                            VillaId = 3
                        },
                        new
                        {
                            VillaNo = 302,
                            SpecialDetails = "Luxury Garden Villa No. 302",
                            VillaId = 3
                        },
                        new
                        {
                            VillaNo = 401,
                            SpecialDetails = "Family Villa No. 401",
                            VillaId = 4
                        },
                        new
                        {
                            VillaNo = 402,
                            SpecialDetails = "Family Villa No. 402",
                            VillaId = 4
                        },
                        new
                        {
                            VillaNo = 501,
                            SpecialDetails = "Honeymoon Suite Villa No. 501",
                            VillaId = 5
                        },
                        new
                        {
                            VillaNo = 502,
                            SpecialDetails = "Honeymoon Suite Villa No. 502",
                            VillaId = 5
                        });
                });

            modelBuilder.Entity("MagicVilla.Domain.Entities.VillaNumber", b =>
                {
                    b.HasOne("MagicVilla.Domain.Entities.Villa", "Villa")
                        .WithMany()
                        .HasForeignKey("VillaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Villa");
                });
#pragma warning restore 612, 618
        }
    }
}
